[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools_scm[toml]>=8.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "seguin_loom_server"
dynamic = ["version"]
description = "Web server that drives a Séguin dobby loom"
readme = "README.md"
dependencies = [
  "base_loom_server >= 0.6",
]
authors = [
  { name="Russell Owen", email="r3owen@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
  "base_loom_server[dev] >= 0.6",
]

[project.scripts]
run_seguin_loom = "seguin_loom_server.main:run_seguin_loom"

[project.urls]
Homepage = "https://pypi.org/project/seguin-loom-server/"
Documentation = "https://r-owen.github.io/base_loom_server/"
Source = "https://github.com/r-owen/seguin_loom_server"
Issues = "https://github.com/r-owen/seguin_loom_server/issues"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.isort]
profile = "black"

[tool.setuptools_scm]
write_to = "src/seguin_loom_server/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""

[tool.mypy]
explicit_package_bases = "True"
